development:
  - name: Ganache CLI (Arbitrum-Mainnet Fork)
    id: arbitrum-main-fork
    cmd: ganache-cli
    host: 127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: arbitrum-main